### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined

### ISSUE THREAD

**Issue by fderyckel** [frappe/school#230]
Having error when trying url
mysite.com/courses

```
Traceback (most recent call last):
  File "/home/flipo/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/flipo/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/flipo/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/flipo/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/flipo/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/flipo/frappe-bench/apps/community/community/./www/courses/index.html", line 2, in top-level template code
    {% from "www/hackathons/macros/card.html" import null_card %}
  File "/home/flipo/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/home/flipo/frappe-bench/apps/community/community/./www/courses/index.html", line 30, in block "content"
    {{ widgets.CourseCard(course=course, read_only=False) }}
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/flipo/frappe-bench/apps/community/community/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/flipo/frappe-bench/apps/community/community/./lms/widgets/CourseCard.html", line 43, in top-level template code
    {{ widgets.Avatar(member=course.get_instructor(), avatar_class="avatar-small") }}
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/flipo/frappe-bench/apps/community/community/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/flipo/frappe-bench/apps/community/community/./community/widgets/Avatar.html", line 2, in top-level template code
    <a class="button-links" href="{{ get_profile_url(member.username) }}">
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/flipo/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined
```

**Comment by fderyckel** [comment]
Thanks for reply.  
Strange, not sure why path is different.  I have installed it on a fresh server with just frappe on it.  No ERPNext.

**Comment by fderyckel** [comment]
> @anandology that shouldn't be the case as the apps name is still community. It's only the repository thats has been renamed to school. Check the path in the traceback attached. It's still apps/community.
> 
> @fderyckel can you please make sure that the apps are completely updated and the cache has been ce leared?

yes I have updated both frappe and school.  and also did run with patches. 
Still same error.

**Comment by pateljannat** [comment]
Can you try installing the app again on a fresh site @fderyckel ?

**Comment by pateljannat** [comment]
Reopen when needed.

**Comment by fderyckel** [comment]
@pateljannat 
Hey Jannat, 
I did reinstall everything, create a course and got again that error.  
I am wondering if it's because I am not on dns.  I just use IP address to access the site.  

There is obviously something with that 'get_profile_url' function that is not working for me for some reason.  😭

**Comment by iMoshi** [comment]
Same error. Tried get-app community (not found), then I've tried install-app community which was also not found. 

Awesome work on the school app!

**Comment by pateljannat** [comment]
@iMoshi The app name is not community anymore. It has been renamed to school. So please try with `bench get-app https://github.com/frappe/school` and then `bench install-app school`

**Comment by pateljannat** [comment]
@fderyckel can you confirm if you tried with school and not community. Also is the traceback the same this time. Your previous traceback had a different path. Is that still the same?

**Comment by iMoshi** [comment]
> @iMoshi The app name is not community anymore. It has been renamed to school. So please try with `bench get-app https://github.com/frappe/school` and then `bench install-app school`

That's exactly what I have tried :) And for some reason, I did not even know there was an app called "community" for Frappe anyways ;p

**Comment by pateljannat** [comment]
@iMoshi can you also share the traceback.

**Comment by iMoshi** [comment]
> @iMoshi can you also share the traceback.

`Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/frappe/bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/frappe/bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/frappe/bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/frappe/bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/bench/apps/school/school/./www/courses/index.html", line 2, in top-level template code
    {% from "www/hackathons/macros/card.html" import null_card %}
  File "/home/frappe/bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/home/frappe/bench/apps/school/school/./www/courses/index.html", line 19, in block "content"
    {{ widgets.CourseCard(course=course, read_only=False) }}
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/bench/apps/school/school/./lms/widgets/CourseCard.html", line 45, in top-level template code
    {{ widgets.Avatar(member=course.get_instructor(), avatar_class="avatar-small") }}
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/bench/apps/school/school/./community/widgets/Avatar.html", line 2, in top-level template code
    <a class="button-links" href="{{ get_profile_url(member.username) }}">
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/frappe/bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined
 `
Oh gee, I think it's looking for .html files in a wrong directory.

**Comment by pateljannat** [comment]
@iMoshi is there any place where I can check your site first hand?

**Comment by fproldan** [comment]
I'm facing the same issue, is this app mentend for use with v13?

**Comment by pateljannat** [comment]
@fproldan can you try the app with Frappe develop branch?

**Comment by Nadorml** [comment]
im facing same issue , any solution here ?

**Comment by fderyckel** [comment]
What I came to I swear and is that it is related to frappe V13 and that
seems to disappear if you use the develop version of frappe.  But not sure

**Comment by Nadorml** [comment]
so , how can i handle using V13 ?

**Comment by M-Tallal-Habib** [comment]
@pateljannat Hi G'Day!
I am facing the same issue of **get_profile_url** error when I try the path <site-name>/courses or <site-name>/courses/<course-name>.
The traceback of full error is given below

Traceback (most recent call last):
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/./www/courses/course.html", line 209, in top-level template code
    {{ frappe.utils.flt(avg_rating, frappe.get_system_settings("float_precision") or 3) }} Rating
  File "/home/vatomaticfrappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/./www/courses/course.html", line 13, in block "content"
    {{ CourseOutlineAndCreator(course) }}
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/./www/courses/course.html", line 117, in template
    {{ widgets.MemberCard(member=course.get_instructor(), show_course_count=True, dimension_class="member-card-large") }}
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/./lms/widgets/MemberCard.html", line 3, in top-level template code
    {{ widgets.Avatar(member=member, avatar_class=avatar_class) }}
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vatomaticfrappe/frappe-bench/apps/school/school/./community/widgets/Avatar.html", line 2, in top-level template code
    <a class="button-links" href="{{ get_profile_url(member.username) }}">
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/vatomaticfrappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined

**Also when I try to hit the path <site-name>/users/ it gives module not found for the frappe.website.page_renderers which is not available in frappe repo but in documentation it is available that seems to very strange.**

Waiting for your kind reply
Regards
Tallal

**Comment by pateljannat** [comment]
@fderyckel @iMoshi @fproldan @M-Tallal-Habib @Nadorml 

As the above discussion suggests this problem is related to frappe v13. School app was developed using frappe develop.

Since a lot of you guys are using Frappe v13, we are planning to have a v13 compatible branch for the School app too. It's a work in progress currently. Will keep you guys updated on the same.

**Comment by alirazzaq88** [comment]
I having the same issue
**jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined**

**Installed:**
bench get-app https://github.com/frappe/school 
bench install-app school

ERPNext: v13.16.1 (version-13)
Frappe Framework: v13.16.0 (version-13)
School: v0.0.1 (main)

Traceback (most recent call last):
  File "/home/roshan/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 86, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 6, in top-level template code
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/roshan/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/roshan/frappe-bench/apps/school/school/./lms/widgets/CourseCard.html", line 45, in top-level template code
    {{ widgets.Avatar(member=course.get_instructor(), avatar_class="avatar-small") }}
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/roshan/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/roshan/frappe-bench/apps/school/school/./community/widgets/Avatar.html", line 2, in top-level template code
    <a class="button-links" href="{{ get_profile_url(member.username) }}">
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
    context = get_context(path)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/context.py", line 97, in build_context
    ret = context.doc.get_context(context)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/doctype/web_page/web_page.py", line 73, in get_context
    self.set_page_blocks(context)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/doctype/web_page/web_page.py", line 126, in set_page_blocks
    out = get_web_blocks_html(self.page_blocks)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/website/doctype/web_page/web_page.py", line 225, in get_web_blocks_html
    'web_template_html': web_template.render(block.web_template_values),
  File "/home/roshan/frappe-bench/apps/school/school/overrides/web_template.py", line 15, in render
    return frappe.render_template(template, values)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 88, in render_template
    throw(title="Jinja Template Error", msg="<pre>{template}</pre><pre>{tb}</pre>".format(template=template, tb=get_traceback()))
  File "/home/roshan/frappe-bench/apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/roshan/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "/home/roshan/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <pre><div>
  <h2 class="section-title">{{ title }}</h2>
  <div class="cards-parent mt-10">
    {% for course_row in courses %}
    {% set course = frappe.get_doc("LMS Course", course_row.course) %}
    {{ widgets.CourseCard(course=course, read_only=False) }}
    {% endfor %}
  </div>
  <a class="button-links d-flex justify-content-center mt-12 intercative-link" style="color: var(--gray-800);" href="/courses">
    <div>
      Explore More
    </div>
    <img src="/assets/school/icons/arrow.svg" class="ml-2"/>
  </a>
</div>
</pre><pre>Traceback (most recent call last):
  File "/home/roshan/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 86, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 6, in top-level template code
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/roshan/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/roshan/frappe-bench/apps/school/school/./lms/widgets/CourseCard.html", line 45, in top-level template code
    {{ widgets.Avatar(member=course.get_instructor(), avatar_class="avatar-small") }}
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/roshan/frappe-bench/apps/school/school/widgets.py", line 64, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/roshan/frappe-bench/apps/school/school/./community/widgets/Avatar.html", line 2, in top-level template code
    <a class="button-links" href="{{ get_profile_url(member.username) }}">
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/roshan/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_profile_url' is undefined
</pre>

**Comment by Nadorml** [comment]
any updates ?

**Comment by pateljannat** [comment]
A new branch called [version-13](https://github.com/frappe/school/tree/version-13) has been created. Please facing this issue should checkout this branch and try the app.

**Comment by Nadorml** [comment]
thank you , kindly advice about below error after install and click learn

![image](https://user-images.githubusercontent.com/50796907/147760538-575bed3c-a506-49b9-a519-efb024e2e69e.png)

**Comment by pateljannat** [comment]
@Nadorml can you let me know what minor version of Frappe App are you on? The error you are facing is because of the Discussions component. This was merged in v13 with v13.17.0.

**Comment by Nadorml** [comment]
Frappe 13.3

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by pateljannat** [comment]
@Nadorml Please update Frappe app to v13.17.0.

**Comment by Nadorml** [comment]
@pateljannat 
thanks for you very mush , 
can you support or guide for Exercise form , how can i create it and documentation for this , code ,  test and answers mean ?

**Comment by pateljannat** [comment]
@Nadorml  The Exercise doctype does not support any task from Frappe or ERPNext. It's meant only for Python Exercises.

**Comment by Nadorml** [comment]
thanks , what in case i need to build quiz but not optional answers , text based , that why i think about Exercise

**Comment by pateljannat** [comment]
> what in case i need to build quiz but not optional answers , text based

We are planning to implement this in the coming weeks. Maybe you can wait till then?
